spring:
  application: 
    name: core-gateway
  servlet:
    multipart:
      maxFileSize: 800MB
      maxRequestSize: 800MB
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            # 允许携带认证信息
            allow-credentials: true
            # 允许跨域的源(网站域名/ip)，设置*为全部
            allowed-origins: "*"
            # 允许跨域请求里的head字段，设置*为全部
            allowed-headers: "*"
            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            allowed-methods: "*"
            # 跨域允许的有效期
            max-age: 3600
      #注册中心服务发现
#      discovery:
#         locator:
#           #开启通过服务中心的自动根据 serviceId 创建路由的功能
#           enabled: true
#           # 配置之后访问时无需大写
#           lower-case-service-id: true
#           predicates[0]:
#             name: Path
#             args[patten]: "'/api/' + serviceId + '/**'"
#           filters[0]:
#             name: RewritePath
#             args[regexp]: "'/api/' + serviceId + '/(?<remaining>.*)'"
#             args[replacement]: "'/${remaining}}'"
#      routes:
#         - id: core-service
#           uri: lb://core-service
#           predicates:
#             - Path= /api/core/**
#           filters:
#             - StripPrefix=2
#         - id: edge-service
#           uri: lb://edge-service
#           predicates:
#             - Path= /api/edge/**
#           filters:
#             - StripPrefix=2
#         - id: user-service
#           uri: lb://user-service
#           predicates:
#             - Path= /api/user/**
#           filters:
#             - StripPrefix=2
#         - id: share-service
#           uri: lb://share-service
#           predicates:
#             - Path= /api/share/**
#           filters:
#             - StripPrefix=2

management:
  endpoints:
    web:
      #Actuator 默认所有的监控点路径都在/actuator/*，当然如果有需要这个路径也支持定制。
      base-path: /monitor
      #Actuator 默认只开放了两个端点 /actuator/health 和 /actuator/info
      exposure:
        #打开所有的监控点
        include: '*'
        #屏蔽env,beans监控点
        exclude: env,beans
  endpoint:
    health:
      #详细显示health信息
      show-details: always
      #启用接口关闭 Spring Boot (post请求)
      shutdown:
        enabled: true
  health:
    defaults:
      enabled: true

    
ribbon: 
  ReadTimeout: 60000
  ConnectTimeout: 60000